### Robustness metrics

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from ema_workbench.analysis import parcoords

C:\Users\thori\Anaconda3\envs\mbdm1\lib\site-packages\ema_workbench\analysis\prim.py:30: ImportWarning: altair based interactive inspection not available
  warnings.warn(("altair based interactive "

In [2]:
results_sc0 = pd.read_csv('outcomes/results_optimisation_scenario0.csv')
results_sc1= pd.read_csv('outcomes/results_optimisation_scenario1.csv')
results_sc2 = pd.read_csv('outcomes/results_optimisation_scenario2.csv')
# results_sc3 = pd.read_csv('outcomes/results_optimisation_scenario3.csv')
# results_sc4 = pd.read_csv('outcomes/results_optimisation_scenario4.csv')

In [3]:
results_sc0['scenario'] = 0
results_sc1['scenario'] = 1
results_sc2['scenario'] = 2
# results_sc3['scenario'] = 3
# results_sc4['scenario'] = 4
results_sc2

,Unnamed: 0,0_RfR 0,0_RfR 1,0_RfR 2,1_RfR 0,1_RfR 1,1_RfR 2,2_RfR 0,2_RfR 1,2_RfR 2,...,A.2_Expected Number of Deaths,A.3 Total Costs,A.3_Expected Number of Deaths,A.4 Total Costs,A.4_Expected Number of Deaths,A.5 Total Costs,A.5_Expected Number of Deaths,RfR Total Costs,Expected Evacuation Costs,scenario
0,0,1,0,1,0,0,0,1,0,1,...,0.000000,0.000000e+00,0.000000,3.567482e+07,0.000000,1.913185e+08,0.000000,1.362500e+09,0.000000,2
1,1,0,0,0,0,0,0,0,1,0,...,0.000000,1.195050e+08,0.000000,1.128741e+08,0.002497,1.473539e+08,0.003159,3.070000e+07,4998.039707,2
2,2,1,0,1,0,1,1,1,0,0,...,0.000000,5.176004e+07,0.000000,2.559863e+07,0.000000,9.676792e+07,0.000000,1.255200e+09,0.000000,2
3,3,0,0,1,0,0,1,1,0,0,...,0.000000,7.278108e+07,0.018450,2.155622e+07,0.000000,1.066149e+08,0.004275,5.755000e+08,0.000000,2
4,4,1,0,1,0,0,0,0,0,0,...,0.000000,1.106486e+08,0.018968,9.695195e+06,0.000000,1.617441e+08,0.000000,9.238000e+08,0.000000,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1303,1303,0,0,0,0,0,0,1,1,0,...,0.000000,7.060438e+07,0.000000,1.854588e+07,0.000000,1.453035e+08,0.001539,3.038000e+08,142.519929,2
1304,1304,0,0,0,0,0,0,0,0,1,...,0.000000,6.101041e+07,0.002266,3.066186e+07,0.000000,8.699192e+07,0.000000,3.943000e+08,301.851821,2
1305,1305,0,0,0,0,0,0,0,1,0,...,0.000000,1.057812e+08,0.005696,4.035960e+07,0.000047,1.896612e+08,0.004501,3.070000e+07,3822.219540,2
1306,1306,0,0,0,0,0,0,0,1,0,...,0.000000,9.471989e+07,0.000000,1.106877e+07,0.000000,1.628858e+08,0.003084,2.731000e+08,1157.028052,2
1307,1307,0,0,0,0,0,0,1,0,0,...,0.011994,1.038094e+08,0.000000,3.424135e+07,0.000000,1.838366e+09,0.725371,3.070000e+07,0.000000,2

In [4]:
all_results = results_sc0.append(results_sc1)
all_results = all_results.append(results_sc2)
# all_results = all_results.append(results_sc3)
# all_results = all_results.append(results_sc4)
all_results = all_results.iloc[:, 1:]
all_results.tail()

,0_RfR 0,0_RfR 1,0_RfR 2,1_RfR 0,1_RfR 1,1_RfR 2,2_RfR 0,2_RfR 1,2_RfR 2,3_RfR 0,...,A.2_Expected Number of Deaths,A.3 Total Costs,A.3_Expected Number of Deaths,A.4 Total Costs,A.4_Expected Number of Deaths,A.5 Total Costs,A.5_Expected Number of Deaths,RfR Total Costs,Expected Evacuation Costs,scenario
1303,0,0,0,0,0,0,1,1,0,1,...,0.000000,7.060438e+07,0.000000,1.854588e+07,0.000000,1.453035e+08,0.001539,303800000.0,142.519929,2
1304,0,0,0,0,0,0,0,0,1,1,...,0.000000,6.101041e+07,0.002266,3.066186e+07,0.000000,8.699192e+07,0.000000,394300000.0,301.851821,2
1305,0,0,0,0,0,0,0,1,0,0,...,0.000000,1.057812e+08,0.005696,4.035960e+07,0.000047,1.896612e+08,0.004501,30700000.0,3822.219540,2
1306,0,0,0,0,0,0,0,1,0,1,...,0.000000,9.471989e+07,0.000000,1.106877e+07,0.000000,1.628858e+08,0.003084,273100000.0,1157.028052,2
1307,0,0,0,0,0,0,1,0,0,0,...,0.011994,1.038094e+08,0.000000,3.424135e+07,0.000000,1.838366e+09,0.725371,30700000.0,0.000000,2

In [5]:
all_results.columns

Index(['0_RfR 0', '0_RfR 1', '0_RfR 2', '1_RfR 0', '1_RfR 1', '1_RfR 2',
       '2_RfR 0', '2_RfR 1', '2_RfR 2', '3_RfR 0', '3_RfR 1', '3_RfR 2',
       '4_RfR 0', '4_RfR 1', '4_RfR 2', 'EWS_DaysToThreat',
       'A.1_DikeIncrease 0', 'A.1_DikeIncrease 1', 'A.1_DikeIncrease 2',
       'A.2_DikeIncrease 0', 'A.2_DikeIncrease 1', 'A.2_DikeIncrease 2',
       'A.3_DikeIncrease 0', 'A.3_DikeIncrease 1', 'A.3_DikeIncrease 2',
       'A.4_DikeIncrease 0', 'A.4_DikeIncrease 1', 'A.4_DikeIncrease 2',
       'A.5_DikeIncrease 0', 'A.5_DikeIncrease 1', 'A.5_DikeIncrease 2',
       'A.1 Total Costs', 'A.1_Expected Number of Deaths', 'A.2 Total Costs',
       'A.2_Expected Number of Deaths', 'A.3 Total Costs',
       'A.3_Expected Number of Deaths', 'A.4 Total Costs',
       'A.4_Expected Number of Deaths', 'A.5 Total Costs',
       'A.5_Expected Number of Deaths', 'RfR Total Costs',
       'Expected Evacuation Costs', 'scenario'],
      dtype='object')

In [6]:
outcomes = all_results.iloc[:, 32:]
outcomes = outcomes.iloc[:, :-1]
experiments = all_results.iloc[:,:31]
experiments['scenario'] = all_results['scenario']

#outcomes.columns

In [9]:
a = all_results.groupby('scenario').mean()
mean = a.loc[2, ['A.5_Expected Number of Deaths']]
a = a.iloc[:, 31:]
a.columns

Index(['A.1 Total Costs', 'A.1_Expected Number of Deaths', 'A.2 Total Costs',
       'A.2_Expected Number of Deaths', 'A.3 Total Costs',
       'A.3_Expected Number of Deaths', 'A.4 Total Costs',
       'A.4_Expected Number of Deaths', 'A.5 Total Costs',
       'A.5_Expected Number of Deaths', 'RfR Total Costs',
       'Expected Evacuation Costs'],
      dtype='object')

In [11]:
overall_scores = {}
sc_regret = []
a = all_results.groupby('scenario').mean()
for scenario in experiments.scenario.unique():
    logical = experiments.scenario==scenario
    temp_results = {k:v[logical] for k,v in outcomes.items()}
    temp_results = pd.DataFrame(temp_results)
    temp_experiments = experiments[experiments.scenario==scenario]
        
    best = temp_results.max()
    best['A.5_Expected Number of Deaths'] = temp_results['A.5_Expected Number of Deaths'].min()    
    scenario_regret = a.loc[scenario, :] - best  
    sc_regret.append(scenario_regret)

In [34]:
sc_regret

0_RfR 0                                   NaN
0_RfR 1                                   NaN
0_RfR 2                                   NaN
1_RfR 0                                   NaN
1_RfR 1                                   NaN
1_RfR 2                                   NaN
2_RfR 0                                   NaN
2_RfR 1                                   NaN
2_RfR 2                                   NaN
3_RfR 0                                   NaN
3_RfR 1                                   NaN
3_RfR 2                                   NaN
4_RfR 0                                   NaN
4_RfR 1                                   NaN
4_RfR 2                                   NaN
A.1 Total Costs                           NaN
A.1_DikeIncrease 0                        NaN
A.1_DikeIncrease 1                        NaN
A.1_DikeIncrease 2                        NaN
A.1_Expected Number of Deaths   -1.599399e+00
A.2 Total Costs                 -1.176545e+09
A.2_DikeIncrease 0                        NaN
A.2_DikeIncrease 1                        NaN
A.2_DikeIncrease 2                        NaN
A.2_Expected Number of Deaths   -5.587692e-01
A.3 Total Costs                 -1.069857e+08
A.3_DikeIncrease 0                        NaN
A.3_DikeIncrease 1                        NaN
A.3_DikeIncrease 2                        NaN
A.3_Expected Number of Deaths   -1.280402e-01
A.4 Total Costs                 -5.727238e+07
A.4_DikeIncrease 0                        NaN
A.4_DikeIncrease 1                        NaN
A.4_DikeIncrease 2                        NaN
A.4_Expected Number of Deaths   -5.748509e-03
A.5 Total Costs                 -1.837337e+09
A.5_DikeIncrease 0                        NaN
A.5_DikeIncrease 1                        NaN
A.5_DikeIncrease 2                        NaN
A.5_Expected Number of Deaths    1.877153e-01
EWS_DaysToThreat                          NaN
Expected Evacuation Costs       -1.021101e+05
RfR Total Costs                 -1.374760e+09
dtype: float64

In [31]:
# fix this
scen_regret = [x for x in sc_regret if pd.isnull(x) == False]
scen_regret

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [32]:
from ema_workbench import Policy

policies = []
for i in enumerate(experiments):
    experiments1 = experiments.iloc[:, :-1]
    for j, row in experiments1.iterrows():
        policy = Policy(f'policy {i} option {j}', **row.to_dict())
        # try to add this to column in dataframe
#         compare = experiments1.iloc[i, :].to_dict()
#         if policy == compare:
#             experiments.loc[i,['policy']] = j
        policies.append(policy)
        #experiments1['policy'] = policy

In [33]:
len(policies)

146272

In [ ]:
for i in range(len(experiments)):
    compare = experiments.iloc[i, :-1].to_dict()
    for j in range(len(policies)):
        policy = policies[j]
        if policy == compare:
            experiments.loc[i, ['policy']] = j

In [29]:
experiments['policy']

{'0_RfR 0': 1,
 '0_RfR 1': 0,
 '0_RfR 2': 0,
 '1_RfR 0': 0,
 '1_RfR 1': 0,
 '1_RfR 2': 0,
 '2_RfR 0': 0,
 '2_RfR 1': 1,
 '2_RfR 2': 0,
 '3_RfR 0': 1,
 '3_RfR 1': 1,
 '3_RfR 2': 0,
 '4_RfR 0': 1,
 '4_RfR 1': 0,
 '4_RfR 2': 1,
 'EWS_DaysToThreat': 3,
 'A.1_DikeIncrease 0': 0,
 'A.1_DikeIncrease 1': 0,
 'A.1_DikeIncrease 2': 4,
 'A.2_DikeIncrease 0': 1,
 'A.2_DikeIncrease 1': 3,
 'A.2_DikeIncrease 2': 3,
 'A.3_DikeIncrease 0': 0,
 'A.3_DikeIncrease 1': 9,
 'A.3_DikeIncrease 2': 8,
 'A.4_DikeIncrease 0': 6,
 'A.4_DikeIncrease 1': 2,
 'A.4_DikeIncrease 2': 0,
 'A.5_DikeIncrease 0': 3,
 'A.5_DikeIncrease 1': 2,
 'A.5_DikeIncrease 2': 3}

In [27]:
policies[0]

ema_workbench.em_framework.parameters.Policy

In [18]:
experiments

,0_RfR 0,0_RfR 1,0_RfR 2,1_RfR 0,1_RfR 1,1_RfR 2,2_RfR 0,2_RfR 1,2_RfR 2,3_RfR 0,...,A.3_DikeIncrease 0,A.3_DikeIncrease 1,A.3_DikeIncrease 2,A.4_DikeIncrease 0,A.4_DikeIncrease 1,A.4_DikeIncrease 2,A.5_DikeIncrease 0,A.5_DikeIncrease 1,A.5_DikeIncrease 2,scenario
0,1,1,0,1,1,1,1,1,0,1,...,2,0,3,6,0,1,10,7,8,0
1,1,0,0,0,0,0,0,1,0,1,...,0,9,8,6,2,0,3,2,3,0
2,0,0,0,0,0,0,0,1,1,1,...,4,8,3,6,0,0,5,9,2,0
3,0,0,1,1,0,0,1,1,1,1,...,10,0,2,4,1,2,9,4,5,0
4,0,0,1,0,0,0,1,0,1,1,...,5,5,10,0,2,4,8,0,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1303,0,0,0,0,0,0,1,1,0,1,...,9,0,2,5,1,0,9,3,2,2
1304,0,0,0,0,0,0,0,0,1,1,...,0,1,2,5,3,2,9,0,1,2
1305,0,0,0,0,0,0,0,1,0,0,...,0,1,5,5,7,2,9,5,0,2
1306,0,0,0,0,0,0,0,1,0,1,...,6,4,2,5,0,0,8,1,1,2
1307,0,0,0,0,0,0,1,0,0,0,...,2,9,4,6,2,4,0,5,1,2

In [17]:
len(policies)

146272

In [20]:
if experiments.loc[:, :-1] == policies[0]:
    experiments['policies']=0
experiments

TypeError: cannot do slice indexing on Index with these indexers [-1] of type int

In [ ]:
for i in range(len(policies)):
    experiments['policies'] =

In [ ]:
regret = pd.concat(regret)
maxregret = regret.groupby('policy').max()

In [ ]:
limits = parcoords.get_limits(maxregret)
paraxes = parcoords.ParallelAxes(maxregret)
paraxes.plot(maxregret)
plt.show()