### Robustness metrics

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
from ema_workbench.analysis import parcoords

C:\Users\thori\Anaconda3\envs\mbdm1\lib\site-packages\ema_workbench\analysis\prim.py:30: ImportWarning: altair based interactive inspection not available
  warnings.warn(("altair based interactive "

In [22]:
results_sc0 = pd.read_csv('outcomes/results_optimisation_scenario0.csv')
results_sc1= pd.read_csv('outcomes/results_optimisation_scenario1.csv')
results_sc2 = pd.read_csv('outcomes/results_optimisation_scenario2.csv')
# results_sc3 = pd.read_csv('outcomes/results_optimisation_scenario3.csv')
# results_sc4 = pd.read_csv('outcomes/results_optimisation_scenario4.csv')

In [24]:
results_sc0['scenario'] = 0
results_sc1['scenario'] = 1
results_sc2['scenario'] = 2
# results_sc3['scenario'] = 3
# results_sc4['scenario'] = 4
results_sc0

,Unnamed: 0,0_RfR 0,0_RfR 1,0_RfR 2,1_RfR 0,1_RfR 1,1_RfR 2,2_RfR 0,2_RfR 1,2_RfR 2,...,A.2_Expected Number of Deaths,A.3 Total Costs,A.3_Expected Number of Deaths,A.4 Total Costs,A.4_Expected Number of Deaths,A.5 Total Costs,A.5_Expected Number of Deaths,RfR Total Costs,Expected Evacuation Costs,scenario
0,0,1,1,0,1,1,1,1,1,0,...,0.0,4.804784e+07,0.000000,2.031906e+07,0.000000,2.060465e+08,0.000012,1.126400e+09,7.893073,0
1,1,1,0,0,0,0,0,0,1,0,...,0.0,1.001085e+08,0.000935,2.155622e+07,0.000000,4.982305e+08,0.019864,8.699000e+08,12963.216545,0
2,2,0,0,0,0,0,0,0,1,1,...,0.0,1.052668e+08,0.000000,1.258646e+07,0.000000,2.128826e+08,0.003471,4.250000e+08,2518.289288,0
3,3,0,0,1,1,0,0,1,1,1,...,0.0,7.523531e+07,0.000000,2.559863e+07,0.000000,1.550429e+08,0.000000,1.014200e+09,0.000000,0
4,4,0,0,1,0,0,0,1,0,1,...,0.0,1.247369e+08,0.000000,2.962923e+07,0.000386,9.645122e+07,0.000000,1.021800e+09,342.058525,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1293,1293,1,0,0,0,0,0,0,0,1,...,0.0,1.250995e+08,0.000000,3.581734e+07,0.000000,1.901877e+08,0.000000,7.350000e+08,0.000000,0
1294,1294,0,1,0,0,0,1,1,0,1,...,0.0,5.408231e+07,0.000000,3.852345e+07,0.000000,1.454613e+08,0.030384,9.835000e+08,0.000000,0
1295,1295,0,1,0,0,0,0,1,1,1,...,0.0,1.101717e+08,0.000000,3.158751e+07,0.000093,1.048825e+08,0.000000,6.752000e+08,118.857163,0
1296,1296,0,1,1,0,1,1,1,1,0,...,0.0,7.976419e+07,0.000000,3.395120e+07,0.000000,1.724097e+08,0.011547,7.874000e+08,0.000000,0
1297,1297,1,0,1,1,0,1,1,1,1,...,0.0,2.879840e+07,0.000000,4.122814e+07,0.000049,4.865487e+08,0.018207,1.209100e+09,12561.019608,0

In [29]:
all_results = results_sc0.append(results_sc1)
all_results.append(results_sc2)
# all_results.append(results_sc3)
# all_results.append(results_sc4)
all_results = all_results.iloc[:, 1:]
all_results.head()

,0_RfR 0,0_RfR 1,0_RfR 2,1_RfR 0,1_RfR 1,1_RfR 2,2_RfR 0,2_RfR 1,2_RfR 2,3_RfR 0,...,A.2_Expected Number of Deaths,A.3 Total Costs,A.3_Expected Number of Deaths,A.4 Total Costs,A.4_Expected Number of Deaths,A.5 Total Costs,A.5_Expected Number of Deaths,RfR Total Costs,Expected Evacuation Costs,scenario
0,1,1,0,1,1,1,1,1,0,1,...,0.0,4.804784e+07,0.000000,2.031906e+07,0.000000,2.060465e+08,0.000012,1.126400e+09,7.893073,0
1,1,0,0,0,0,0,0,1,0,1,...,0.0,1.001085e+08,0.000935,2.155622e+07,0.000000,4.982305e+08,0.019864,8.699000e+08,12963.216545,0
2,0,0,0,0,0,0,0,1,1,1,...,0.0,1.052668e+08,0.000000,1.258646e+07,0.000000,2.128826e+08,0.003471,4.250000e+08,2518.289288,0
3,0,0,1,1,0,0,1,1,1,1,...,0.0,7.523531e+07,0.000000,2.559863e+07,0.000000,1.550429e+08,0.000000,1.014200e+09,0.000000,0
4,0,0,1,0,0,0,1,0,1,1,...,0.0,1.247369e+08,0.000000,2.962923e+07,0.000386,9.645122e+07,0.000000,1.021800e+09,342.058525,0

In [31]:
all_results.columns

Index(['0_RfR 0', '0_RfR 1', '0_RfR 2', '1_RfR 0', '1_RfR 1', '1_RfR 2',
       '2_RfR 0', '2_RfR 1', '2_RfR 2', '3_RfR 0', '3_RfR 1', '3_RfR 2',
       '4_RfR 0', '4_RfR 1', '4_RfR 2', 'EWS_DaysToThreat',
       'A.1_DikeIncrease 0', 'A.1_DikeIncrease 1', 'A.1_DikeIncrease 2',
       'A.2_DikeIncrease 0', 'A.2_DikeIncrease 1', 'A.2_DikeIncrease 2',
       'A.3_DikeIncrease 0', 'A.3_DikeIncrease 1', 'A.3_DikeIncrease 2',
       'A.4_DikeIncrease 0', 'A.4_DikeIncrease 1', 'A.4_DikeIncrease 2',
       'A.5_DikeIncrease 0', 'A.5_DikeIncrease 1', 'A.5_DikeIncrease 2',
       'A.1 Total Costs', 'A.1_Expected Number of Deaths', 'A.2 Total Costs',
       'A.2_Expected Number of Deaths', 'A.3 Total Costs',
       'A.3_Expected Number of Deaths', 'A.4 Total Costs',
       'A.4_Expected Number of Deaths', 'A.5 Total Costs',
       'A.5_Expected Number of Deaths', 'RfR Total Costs',
       'Expected Evacuation Costs', 'scenario'],
      dtype='object')

In [ ]:
overall_scores = {}
regret = []
for scenario in experiments.scenario.unique():
    logical = experiments.scenario==scenario
    temp_results = {k:v[logical] for k,v in outcomes.items()}
    temp_results = pd.DataFrame(temp_results)
    temp_experiments = experiments[experiments.scenario==scenario]
        
    best = temp_results.max()
    best['max_P'] = temp_results.max_P.min()
    scenario_regret = a - best
    scenario_regret['policy'] = temp_experiments.policy.values    
    regret.append(scenario_regret)

In [ ]:
regret = pd.concat(regret)
maxregret = regret.groupby('policy').max()

In [ ]:
limits = parcoords.get_limits(maxregret)
paraxes = parcoords.ParallelAxes(maxregret)
paraxes.plot(maxregret)
plt.show()